### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by KeironO** [AberystwythSystemsBiology/LImBuS#115]
**Is your feature request related to a problem? Please describe.**

Would be a smart idea of have some form of VERSION file that we can read in to determine what version of limbus is being run. Would also help with CD.

**Describe the solution you'd like**
A file called VERSION in app that just says what version is being run. We could then read this in and have it as a global variable that can be used when rendering templates and such.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pramod74** [comment]
Hi @KeironO,

I would like to work on this issue. Can you please guide me further on what needs to be done here?

Thanks,
Pramod

**Comment by KeironO** [comment]
>  A file called `VERSION` in app that just says what version is being run. We could then read this in and have it as a global variable that can be used when rendering templates and such.

**Comment by pramod74** [comment]
Thanks @KeironO.

I have added a VERSION file, and submitted a PR. Kindly review.

Thanks,
Pramod
