### ISSUE TITLE
Navigating back to sample shipments page after updating status

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#127]
Please could the system navigate back to the sample shipment index after a shipment has been updated. At the moment, it does not do this. 

![image](https://user-images.githubusercontent.com/98022410/150119996-3597ada3-e2b0-408f-b5cb-06a64ce3e356.png)

Kind regards

Anthony

**Comment by ghost** [comment]
Hey @KeironO, I want to solve that issue.
But, how to run this project on windows operating system.

**Comment by KeironO** [comment]
Hi there,

Good to hear! If you're familiar with docker, then it's easy to get started - read the deployment documentation here:

https://limbus.readthedocs.io/en/dev/deployment/external.html

The solution for this is pretty easy, but feel free to ask if you get stuck.

Welcome to the project.

KeironO.

**Comment by KeironO** [comment]
Done :tada:
