### ISSUE TITLE
Cannot batch destroy samples

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#128]
I have attempted a batch disposal event from the sample cart, but get an error message when staging the disposal. 

I created 10 samples, carried out a sample shipment from test site to PPH, batch reviewed samples, and then attempted to destroy them.

![image](https://user-images.githubusercontent.com/98022410/150120939-6d2ab807-5adb-4ebd-8b9a-0816dedd6f25.png)

Kind regards

Anthony

**Comment by pipaLU** [comment]
I will work on this. There are already revisions.

**Comment by pipaLU** [comment]
The error message says no disposal instruction. It might be the case that when doing review, a disposal instruction hasn't been added yet. The box for disposal instruction should be checked and additional info is needed for disposal

**Comment by KeironO** [comment]
@pipaLU would I be right in saying that there's a hard dependency between Sample and Disposal Information?

**Comment by pipaLU** [comment]
> 

There is a disposal id which is nullable for each sample. Disposal info can be null when creating the sample, however can be added later on via sample review or consent withdraw.

**Comment by pipaLU** [comment]
Issue closed. But it is linked to the documentation issue.
