### ISSUE TITLE
Project member has added a rack to the cart and I can't fix it

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#131]
Hi, 

A member of the project team has accidentally added an entire rack of samples into her cart (actual samples, not practice ones). 

I couldn't fix this as an admin, as the rack disappeared. She provided me her login details for me to take a look. I can see all of the samples in the cart (LIMBRACK-11), but the system is freezing and very slow (perhaps due to the number of samples in the cart). I have attempted to delete the samples from the cart, but nothing is happening. 

Please can you help.

![image](https://user-images.githubusercontent.com/98022410/150164194-1a0ea84f-4a85-4870-bb42-1310dde3d0fa.png)

**Comment by KeironO** [comment]
Are any errors being returned?

**Comment by anthonyhorlock** [comment]
No, I'm clicking on the bin icon, with the samples ticked but nothing is happening.

**Comment by KeironO** [comment]
One for Chuan to take a look at I think.

**Comment by anthonyhorlock** [comment]
No problem! I've also attempted to create a new rack and add samples back into it, but that won't work either.  
![image](https://user-images.githubusercontent.com/98022410/150170979-e266cd32-0c02-4b99-8af9-f99d0c7ef82f.png)

**Comment by pipaLU** [comment]
To solve it without changing the code would be ask the project member to delete the sample from the user sample cart first.
In the future, a feature is to be added to allow admin to manage the sample cart including removing it from other user's sample cart.

**Comment by KeironO** [comment]
@anthonyhorlock could you please ask the project member to delete the sample from the user sample cart please?

**Comment by anthonyhorlock** [comment]
This issue has now been fixed - thank-you!
