### ISSUE TITLE
System very slow when attempting to ship, batch review or destroy samples

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#137]
The database is very slow today, particularly when I am testing out the new functions in the sample cart. 

(Note from Keiron: I've removed your instance URL)

![image](https://user-images.githubusercontent.com/4386515/150361442-b1bf1424-773b-4b28-9314-a2e126166001.png)

**Comment by KeironO** [comment]
I have absolutely zero idea what web server this instance is using!

![image](https://user-images.githubusercontent.com/4386515/150360983-6a9880f7-9639-4638-8908-cc6775605180.png)

I've not seen 'Server Hangup' from either `apache` nor `nginx` before. I'm in work until 5.30pm but can I borrow some of your time this evening @pipaLU to get the logs please?

**Comment by pipaLU** [comment]
> 

I could try to increase the memory allocation to the website and see if it improved.

**Comment by KeironO** [comment]
@anthonyhorlock did the memory allocation increase help?

**Comment by anthonyhorlock** [comment]
Hi Keiron. Sorry about the delay in getting back to you! 

Yes, the system seems to be alot quicker now when carrying out batch functions in the sample cart. Thank-you!
