### ISSUE TITLE
Samples are in my cart, but can't add them to a rack

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#138]
Hello, 

Similar to the issues I had yesterday. I am attempting to test a workflow, where samples are created, stored, shipped, reviewed and put back into a rack:

I have created 10 new samples and added them to a rack. 

I then added the rack to the cart, and shipped it, updating the delivery to delivered, and added the samples to the cart.

I then batch reviewed the samples in the cart and added no disposal instruction

I then attempted to put the samples from the cart into a rack that I created, but get this error message

![image](https://user-images.githubusercontent.com/98022410/150362306-0d5498a5-73ee-450a-9971-f3af0738f764.png)

**Comment by pipaLU** [comment]
> 

I think you have been taking actions on rack, not adding samples to rack, therefore the available action for this whole rack is to go to a shelf and add the rack to the shelf rather than adding individual samples to the rack.

**Comment by anthonyhorlock** [comment]
Thank-you! I didn't realise that I could add a whole rack onto a shelf from my cart! Up until now, I have been trialling the functions out with individual samples.

**Comment by anthonyhorlock** [comment]
Thank-you! I didn't realise that I could add a whole rack onto a shelf from my cart! Up until now, I have been trialling the functions out with individual samples.
