### ISSUE TITLE
Add option to delete documents 

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#139]
Please can an option be added, so that documents can be deleted by an admin. 

Also, please can an option be added so that individual files within documents can be deleted. 

![image](https://user-images.githubusercontent.com/98022410/150509188-135344d3-60fb-4e08-bb61-db35bf034a22.png)

**Comment by pipaLU** [comment]
Yes, a feature in the pipeline.

**Comment by KeironO** [comment]
I have a fork of this on my local machine @pipaLU. I'm working late tonight, but I'll merge tomorrow morning as it's already done.

**Comment by KeironO** [comment]
Turns out I didn't have a local branch that I could use (was part of the Containers 2.0 branch that we decided to drop).

Fixed with #157.
