### ISSUE TITLE
Add option to delete attributes

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#140]
Please can an option be added to delete attributes by an admin. 

![image](https://user-images.githubusercontent.com/98022410/150509804-264b1ea1-39f8-4917-b42d-fa18b23f8372.png)

**Comment by pipaLU** [comment]
Sure. this feature is now added to the new feature pipeline.

**Comment by KeironO** [comment]
I also have this in another fork somewhere.

**Comment by pipaLU** [comment]
> 

Can I work on this as it is almost done. Now move on to sample attribute association deletion.
