### ISSUE TITLE
Make 'Processed by' and 'Derived by' sections compulsory 

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#145]
![image](https://user-images.githubusercontent.com/98022410/151781411-f199dfbf-08b2-432a-9b76-bcf63261478a.png)

**Comment by KeironO** [comment]
Fixed.

**Comment by anthonyhorlock** [comment]
Hi Keiron, I did test this out but the sections were not compulsory when I tried them. Are the changes live yet?
