### ISSUE TITLE
Issue when creating a new rack

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#147]
I am getting an error when I have created a new rack, and again when I am attempting to assign the rack to a shelf:

![image](https://user-images.githubusercontent.com/98022410/151783388-15fbe7db-b9fd-4afe-a9c2-227441a65f1f.png)

**Comment by anthonyhorlock** [comment]
Hi Chuan, 

So, this error message appears to be an issue with my admin account, because I can create and assign the rack when I am signed in as a project member

**Comment by pipaLU** [comment]
Fixed in #170
