### ISSUE TITLE
Incorrect Default Biohazard Level

### ISSUE THREAD

**Issue by KeironO** [AberystwythSystemsBiology/LImBuS#150]
**Describe the bug**

For whichever reason, the default biohazard level starts at Two. Weird bug, but it may have been intentional?

**Expected behavior**

Should be Level One?

**Screenshots**

![image](https://user-images.githubusercontent.com/4386515/152402189-2874d38c-e866-44da-8e61-cac67ce3155f.png)

**Comment by pipaLU** [comment]
Level two is the most popular value (e.g. blood) for our test biobank, therefore the default is set to two to increase data input efficiency for our test.

**Comment by KeironO** [comment]
Thank you for clearing that up :D
