### ISSUE TITLE
No error reported when removing protocols with dependent samples

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#152]
> Original Title: Can't delete certain protocols

I have tried to delete the oral wash protocol (which has Sample dependencies), as well as the test disposal protocol. However, when I click remove, nothing happens. 

![image](https://user-images.githubusercontent.com/98022410/152559550-6040e4ec-16e0-4a4f-8f6a-0f393d727daa.png)

**Comment by KeironO** [comment]
I'm unable to replicate this on my end. Just to confirm, this is just a single protocol with no samples associated with it?

**Comment by KeironO** [comment]
It wouldn't be a bad idea if we added this to our automated CI testing pipeline.

**Comment by anthonyhorlock** [comment]
Hi both, 

I have revisited this issue -  I get a message that there are samples associated with the protocol that I am trying to delete (not sure if this message came up before). I have created a new protocol and successfully deleted it, so I think this problem is solved :)

**Comment by KeironO** [comment]
Things shouldn't be breaking that vaguely. You should at least be prompted that it was an issue due to dependent samples

I'm going to change the original Issue title, if that's ok with you @anthonyhorlock

**Comment by anthonyhorlock** [comment]
Sorry, I did now get a message saying there were samples associated with the protocol, so I think the problem is resolved?

![image](https://user-images.githubusercontent.com/98022410/153186304-06f392e1-bfbf-4904-a3ee-3a1618c776d6.png)

**Comment by KeironO** [comment]
My favorite type of bug, the one that has already been fixed.

Thank you @pipaLU
