### ISSUE TITLE
Can't change affiliated or working sites in the user accounts

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#161]
In user accounts (as admin), I am only assigned the testing biobank as my working site. I then went into several project member profiles and realised that I could not change their affiliated site, and the only option I get for their working site is the testing biobank. 

Please can you look into this

![image](https://user-images.githubusercontent.com/98022410/152775760-8ac59f69-5841-466c-8858-5c33e96efc40.png)

**Comment by KeironO** [comment]
Unable to replicate:

![image](https://user-images.githubusercontent.com/4386515/152777679-e4e31c8b-0af4-46f7-9ed7-401da984f1f5.png)


Can you do me a favour and send me the limbus instance URL you're testing on through email please?

**Comment by anthonyhorlock** [comment]
Sure, I'm a little unsure how to do this though! Am I just sending you the web address?

[REMOVED INSTANCE URL]

**Comment by KeironO** [comment]
![image](https://user-images.githubusercontent.com/4386515/152778682-6f7e3a44-8bf5-4769-b9f5-53a6fd5cc3a0.png)

Seems to be fine on my end.

Just to 100% confirm, the user email is: R_n__.M.L_osl_y@wales.nhs.uk?

**Comment by anthonyhorlock** [comment]
Yes, that's right. I think there is a problem with my admin account which might be linked to my inability to store racks, as well as select the working sites (for myself, and for others). It may also be linked to my inability to access the audit function

**Comment by pipaLU** [comment]
> 

Can you test the updated system now? It should fixed your previous issues in access to audit function and moving rack to shelf?

**Comment by anthonyhorlock** [comment]
Yes, that's great! I can access the audit function, move racks to shelf, and assign users different sites! Thank-you!
