### ISSUE TITLE
Error message when I try to access a document 

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#162]
Bit of a random one, but I went into documents and attempted to access a document that I had uploaded. However, It came up with an error message when I clicked the link 

Also, I don't have options to delete documents or attributes yet. I'm not sure if this will be on a future version. 

![image](https://user-images.githubusercontent.com/98022410/152782655-0bedd78d-d16c-46a2-a27d-4231d111c13e.png)

**Comment by KeironO** [comment]
Regarding Document deletion: https://github.com/AberystwythSystemsBiology/limbus/pull/157

Feature added, but no idea when you'll receive it.

**Comment by KeironO** [comment]
Found the problem.

Will push a PR after work.

**Comment by KeironO** [comment]
Fixed.
