### ISSUE TITLE
Simplify audit function

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#163]
Hi Chuan & Keiron, 

I think that to begin with, simplifying the content of the audit trail is the priority; there is too much info there. 

Possibly, with new samples, we could just report the basics, such as...derivative = 'serum'; Trial ID = 'PPH001'; sample ID = '1532'; site ID = 'PPH'

When an edit takes place, perhaps just a summary of the action, such as...Trial ID = 'PPH001'; sample ID = '1532'; volume changed from 0.1 to 0.5, processed by changed from PSG to AH

![image](https://user-images.githubusercontent.com/98022410/152802843-5cbd4a03-dc12-4105-8c1c-e9e0bc9e15ff.png)

**Comment by KeironO** [comment]
@pipaLU I'm working on this right now :laughing:
