### ISSUE TITLE
Creating new sample - Study/Trial info does not expand when selected

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#164]
When creating a new sample, I have selected the study/trial in the option box (in the freezer log consent), but the page does not expand to be able to enter Trial ID etc. This has happed since the last update. 

The system won't let me progress past this page. 

![image](https://user-images.githubusercontent.com/98022410/152803510-2b612a1b-a049-4338-87f4-c881c260bca6.png)

**Comment by KeironO** [comment]
Can you press Ctrl + F5 and try again.

Thanks.

**Comment by anthonyhorlock** [comment]
Sorry, that did not work

**Comment by KeironO** [comment]
Huh, that's strange.

**Comment by KeironO** [comment]
![image](https://user-images.githubusercontent.com/4386515/152804380-a44d95e9-2fe4-406f-8684-a8fee14387cd.png)

This works on my computer...

**Comment by anthonyhorlock** [comment]
That's really odd because I also logged in under the project member account and have the same issue

**Comment by KeironO** [comment]
Are you on Teams? Would you mind screen sharing?

**Comment by KeironO** [comment]
Fixed.

Note: Refreshed whilst holding down control fixed the problem ;)
