### ISSUE TITLE
New Logo Design?

### ISSUE THREAD

**Issue by KeironO** [AberystwythSystemsBiology/LImBuS#168]
# Symbol and logotype reversed out of panels of LImBuS publicity blue.

![image](https://user-images.githubusercontent.com/4386515/152838332-f3d4b64a-09e1-4182-a633-162ad8fa1d1d.png)

# Symbol reversed out of panel of LImBuS publicity blue, logotype reversed out of solid or tone panel of black.

![image](https://user-images.githubusercontent.com/4386515/152838425-cc3b2949-acde-4148-ab0e-6d4ed77611e3.png)

# Symbol and logotype in LImBuS publicity blue reversed panels

![image](https://user-images.githubusercontent.com/4386515/152838587-0398f624-c6c1-4dc1-b319-4c022c426b86.png)

# Symbol in LImBuS PUBLICITY BLUE and logotype in in black within reversed panels

![image](https://user-images.githubusercontent.com/4386515/152838803-cad164a0-8c7e-4309-85ce-6125ba9a9181.png)

**Comment by pipaLU** [comment]
It should be good to have some bold logo with thick borders. But I would still prefer to keep some versions without borders, just like the old ones.
