### ISSUE TITLE
Can't delete document

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#171]
Good morning! 

Sorry if this is an issue that you are already working on, but I still get an error message when I try to access the document in LIMBDOC-1. 

Also, if I try to delete the document, it won't let me:

![image](https://user-images.githubusercontent.com/98022410/153164122-7231108a-e0d1-44a4-b3c3-52c6a8fa753b.png)

**Comment by KeironO** [comment]
Is there any spacing on the end or at the start?

**Edit:** Confirmed to only be a problem for this particular file.

**Comment by KeironO** [comment]
An edge case, for sure. Just tested it with a different file and it worked fine, but for this particular one it fails.

Waiting for @pipaLU to update the system as so I can get a stacktrace out.

**Comment by anthonyhorlock** [comment]
No, there's no spacing differences I'm afraid. I just copied and pasted it directly in (checking for spaces)

**Comment by KeironO** [comment]
I'm just waiting for @pipaLU to get around to updating your instance with the new error handler (I don't have access to system logs) so I can see what is being thrown.

**Comment by pipaLU** [comment]
I'll update the instance today. The error log says:
`````
web 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/limbus/app/document/routes.py", line 221, in view_file
    d = response.headers["content-disposition"]
  File "/usr/local/lib/python3.6/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
ERROR:root:('Code: df05ebc7', KeyError('content-disposition',))"
```

**Comment by KeironO** [comment]
@pipaLU This was fixed in the last update.

https://github.com/AberystwythSystemsBiology/limbus/pull/165

**Comment by KeironO** [comment]
Eh, the problem still persists - but _only_ for this one file in particular.

What a weird bug.

**Comment by anthonyhorlock** [comment]
I now get a detailed error message when I try to open the folder:

'''Traceback (most recent call last):  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request    rv = self.dispatch_request()  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)  File "/limbus/app/decorators.py", line 81, in decorated_function    return f(*args, **kwargs)  File "/limbus/app/document/api.py", line 227, in document_file_get    f = open(file.path, "rb").read()FileNotFoundError: [Errno 2] No such file or directory: '/limbus/documents/Gas Safe Interactive - Learner Guidance  Support v1.13.pdf''''

**Comment by anthonyhorlock** [comment]
Just to add to that, I have also managed to upload another file to LIMBDOC-1, and then download it with no problems. 

I have also successfully deleted it.

**Comment by anthonyhorlock** [comment]
There is something that the system doesn't like about that particular file name. I have uploaded a few variations of file names, and have been able to delete them all. 

I uploaded the same file, and can download them both now, but now can't delete either of them!

**Comment by KeironO** [comment]
I'm as lost as you are. I'll have to look into it after work, could you upload the file here so I can play around with it?

**Comment by anthonyhorlock** [comment]
[Gas Safe Interactive - Learner Guidance  Support v1.13.pdf](https://github.com/AberystwythSystemsBiology/limbus/files/8040256/Gas.Safe.Interactive.-.Learner.Guidance.Support.v1.13.pdf)

**Comment by KeironO** [comment]
![image](https://user-images.githubusercontent.com/4386515/153469538-4e43e432-152c-45bd-935f-5c31acf08e9b.png)
