### ISSUE TITLE
Navigate back to Shipment index page after adding samples to cart

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#175]
Hi, 

Just a small feature - please can the page automatically navigate back to the shipment index one the samples have been added to the cart. For me, this just allows me to see that the shipment is closed, before I rack the samples:

![image](https://user-images.githubusercontent.com/98022410/153401565-d8e2fb3b-cdb4-4422-ae75-c22c54dd6cf4.png)

**Comment by pipaLU** [comment]
sorted in #197
