### ISSUE TITLE
Project member cannot see all shipments for working site

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#176]
I've been playing around with two test project accounts that I have created (one PPH, and one GGH), so that I can ship samples between sites as a project member, rather than an admin. 

I've noticed that I can't see a history of the shipments for the site that I am working on:

![image](https://user-images.githubusercontent.com/98022410/153404293-d305948c-2f02-4ace-b925-233178e9e9dc.png)

If I do see shipments in the index, not all of them are there 

![image](https://user-images.githubusercontent.com/98022410/153404759-a880d44d-f4b4-4f21-b48d-5d2a5d6f1434.png)

However, in the admin account they are all there:

![image](https://user-images.githubusercontent.com/98022410/153404859-48e4697d-1404-4de1-8e30-39e0f42277c0.png)

**Comment by pipaLU** [comment]
> 

This is intended. Once samples were shipped to another site, shipped samples will have a new current_site_id and thus won't be seen by members who do not have permissions for that site. But maybe it is better to allow the user to view the shipment history.

**Comment by KeironO** [comment]
I'm of the view that a user shouldn't be able to see anything related to a site that is outside of what has been explicitly set on their profile - so I wouldn't fix.

**Comment by anthonyhorlock** [comment]
Hi Keiron & Chaun, 

I'll test the shipments out a little more between my different project member accounts, and get back to you asap.
