### ISSUE TITLE
Explicit yes/no for Patient Consent

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#178]
Whilst getting staff trained and practicing with the database, staff have been creating dummy samples. I've noticed that it is a pretty consistent error that the staff aren't checking the box for freezer log consent. 

Understandably, when there is a full list of questions for a real consent form, there will be questions that a participant doesn't agree to. 

Is there a way to adapt the consent list to a yes/no option basis? That way, the freezer log (or any other) consent wouldn't allow you to progress without selecting a 'no' answer. 

Obviously, we could address this as a training issue, but I'm just wondering if it would be difficult to do?

![image](https://user-images.githubusercontent.com/98022410/153894823-ba38205c-fb16-470b-ba98-9acc00757672.png)

**Comment by KeironO** [comment]
If this is specifically about the view you've presented in your screenshot, I actually have no idea what has happened there. Last time I looked at it it was a clear green and red indicator as to whether consent has been provided.

**Comment by anthonyhorlock** [comment]
I think the original view removed the question if it wasn't selected. This caused problems for me when testing, because it needed to be more obvious where a donor might not have consented to their samples being used for genetic testing (for example). I have no problem with the way that this is currently displayed. 

I think that this is mostly a training issue around the freezer log side of things. I am just exploring whether we could make it a yes & no type selection, so that staff couldn't progress without providing an answer.

**Comment by KeironO** [comment]
So like an explicit response, as opposed to it defaulting to no?

Sure, I can get this done pretty quickly if it's how you want to work.

**Comment by anthonyhorlock** [comment]
Yes, if it's easy enough to do then please do it. 

I think that as a freezer log, providing default options, and making certain sections impossible to move on without ticking a box etc., makes us audit compliant without really needing to do anything.

**Comment by pipaLU** [comment]
sorted with additional validation to make sure at least 1 question is checked in #197
