### ISSUE TITLE
Multiple tab opening 

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#179]
Please can the database be kept within a single tab for all operations. I've noticed that when selecting the parent sample from the sample index, a new tab opens. 

I'll update this thread if I come across other sections that also do this:

![image](https://user-images.githubusercontent.com/98022410/154057980-5cf6d5e9-3f82-4f8a-945a-1ba48f1eaa8d.png)

**Comment by KeironO** [comment]
Would be nice to get some community involvement. All that needs to be done here is for all "_blank" instances to be removed from all javascript and jinja templates.
