### ISSUE TITLE
Add volume into quantity for aluquots/derivative 

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#182]
Please can you add text next to volume to indicate that this is in ml. 

Also, the first derivative/aliquot added has the nice short list of blood derivatives, the each subsequent one added has the full list. Please can it be made so that all of the aliquots/derivatives have the same lists?

![image](https://user-images.githubusercontent.com/98022410/154797252-612618c0-70c0-4b53-a8c4-0b4724f7af35.png)

**Comment by pipaLU** [comment]
Fixed in #197
