### ISSUE TITLE
limbus-bwd reports error: venv/bin/pip not found

### ISSUE THREAD

**Issue by rob-a-bolton** [AberystwythSystemsBiology/LImBuS#19]
**Describe the bug**
When attempting to build with `limbus-bwd`, the build reports `sh: 1: ./venv/bin/pip: not found` twice

**To Reproduce**
1. Run `limbus-bwd` in *LImBuS*
2. See error

**Expected behavior**
No reported failure finding pip

**Desktop (please complete the following information):**
 - OS: Fedora 31

**Comment by KeironO** [comment]
I've looked into this, and have been unable to reproduce on any system. That being said, I am going to spend a bit of time today sorting out deployment as it's a bit of a mess right now.

**Comment by KeironO** [comment]
Deployment fixed. Thanks for the heads up.
