### ISSUE TITLE
Adding compartments into the rack location

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#193]
Would it be possible to add a compartment designation (A-Z) to the shelf numbers? This wouldn't necessarily need to be added to the dropdown index below:

![image](https://user-images.githubusercontent.com/98022410/157895440-f78bac93-c58e-49b7-9228-23a95894bba4.png)

However, for now, I'm thinking just an optional setting when allocating a rack to a shelf, where a compartment could be allocated e.g. Shelf 1, compartment A. 

We typically have drawers in the -80 C freezers, and this would help to further identify the location of the racks within the freezer.

**Comment by pipaLU** [comment]
> 

I am wondering if this function could be achieved by have more detailed shelf name, e.g. shelf1-A, shelf1-B? Original design assumes that shelf info is relatively stable, attaching to the cold storage.

**Comment by KeironO** [comment]
After two years of development, I've come to realise that we're probably too rigid in much of what we do when it comes to how storage is managed. The only real problem is that the amount of work required to go 'dynamic' is a full-time job.

**Comment by anthonyhorlock** [comment]
Yes, I think that keeping the shelf info 'stable', as in Shelves 1-4 etc. will always be stable in terms of the cold storage that we have. 

The A-Z compartment designations are more of a 'descriptor', that will be assigned to the rack and have an additional column added to the storage portal index after 'Shelf'. I don't think it would require a hyperlink like the 'Rack' or 'Shelf' columns. I hope that makes sense! 

![image](https://user-images.githubusercontent.com/98022410/159474732-c3b1af31-f5aa-4e21-8e91-3b8fa0f60d37.png)

**Comment by anthonyhorlock** [comment]
An additional option in the rack creation stage would hopefully solve this issue. An empty compartment box to input a letter (A-Z) under 'Shelf' would be enough:

![image](https://user-images.githubusercontent.com/98022410/200818922-222bac5e-409d-46b5-8973-f2f26a7b29d1.png)


Within the shelf view, an extra column to indicate the letter inputted would be nice. Perhaps after the 'Rack' column (if inputting A-Z, it would be great if this would be listed alphabetically):

![image](https://user-images.githubusercontent.com/98022410/200819385-ae5e2855-b1f5-4d4f-b585-a75a82e2f4a4.png)


In the storage portal, an additional column after 'Shelf' would be great, as it would make it easy to identify where a rack was located (e.g., Top Shelf, Compartment A):

![image](https://user-images.githubusercontent.com/98022410/200819725-0552ab96-c716-40a2-8fc5-f3e314a44d7a.png)
