### ISSUE TITLE
Adding a warning for duplicate trial number

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#196]
Would it be possible to add a warning when a user enters a participant ID that is a duplicate? We don't want to stop this from happening, because some trials require multiple visits. However, a warning to tell the user that this is a duplicate ID would prevent issues where samples might be allocated the same ID by accident. 

![image](https://user-images.githubusercontent.com/98022410/165330223-d8574cbc-c3fd-476d-b6da-082e9bf36074.png)

**Comment by pipaLU** [comment]
Sorted in #197
