### ISSUE TITLE
Error when sending a password reset link

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#199]
Hello, 

I am receiving this error when trying to send a password reset link. Please could you look into it for me:

'''Traceback (most recent call last):  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request    rv = self.dispatch_request()  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)  File "/limbus/app/decorators.py", line 28, in decorated_function    return f(*args, **kwargs)  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view    return func(*args, **kwargs)  File "/limbus/app/admin/routes/auth.py", line 210, in admin_password_reset    mail.send(msg)  File "/usr/local/lib/python3.8/dist-packages/flask_mail.py", line 491, in send    with self.connect() as connection:  File "/usr/local/lib/python3.8/dist-packages/flask_mail.py", line 144, in __enter__    self.host = self.configure_host()  File "/usr/local/lib/python3.8/dist-packages/flask_mail.py", line 165, in configure_host    host.login(self.mail.username, self.mail.password)  File "/usr/lib/python3.8/smtplib.py", line 743, in login    raise last_exception  File "/usr/lib/python3.8/smtplib.py", line 732, in login    (code, resp) = self.auth(  File "/usr/lib/python3.8/smtplib.py", line 655, in auth    raise SMTPAuthenticationError(code, resp)smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials w7-20020adfde87000000b0022afedf3c87sm11985531wrl.105 - gsmtp')'''

**Comment by KeironO** [comment]
Sounds like an issue with the account used to send emails:

@pipaLU

**Comment by pipaLU** [comment]
The issue with the email account has been sorted.
