### ISSUE TITLE
Issue with container types

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#200]
The new container types (15 ml Falcon tubes/1000 ul Biobank tubes) are raising an error message when I submit them when deriving a sample. Please could you take a look. 

![image](https://user-images.githubusercontent.com/98022410/200814096-afccc55c-8545-432d-baf1-84acc15dc6fb.png)

**Comment by pipaLU** [comment]
This should have been sorted.
