### ISSUE TITLE
Option to lock consent forms is not working 

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#204]
I don't seem to have the ability to 'lock' consent forms. Would this then remove them as an option as a consent template when assigning a new consent to a donor? That would be very useful! 

![image](https://user-images.githubusercontent.com/98022410/200827663-914ab69f-3b12-4843-92d5-fd3df3b3e078.png)

**Comment by KeironO** [comment]
That's strange. Are you using your wales.nhs.uk email?

**Comment by anthonyhorlock** [comment]
Hi Keiron! Yes, I've just double checked, and I am using my admin account (wales.nhs.uk).

**Comment by KeironO** [comment]
Drop me a call on Teams and we'll investigate.

**Comment by anthonyhorlock** [comment]
Please can the lock function for consents be activated, so that they no longer appear as options for new donors? (similar to the lock function for protocols and sites). 

It would also be great if there was a 'remove' option, so that consents that don't have donors/samples associated with it could be removed 

![image](https://user-images.githubusercontent.com/98022410/210541369-224adf96-5802-4762-89cb-37c5e211f616.png)
