### ISSUE TITLE
Samples to be assigned to cells to follow the last sample entry

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#205]
At the moment, if there are gaps in a sample entry into a rack, the database automatically allocates new samples to the missing cells (e.g., E4, B5, B7 of the example below). We then need to drag the new samples into the correct positions in the rack. Is there a way that sample allocation could follow on from the last sample in the rack (e.g., J8, A9, B9 etc.... in this example):

![image](https://user-images.githubusercontent.com/98022410/200828551-6718b978-ab10-4e16-88b2-a129d5497cce.png)

**Comment by pipaLU** [comment]
Fix in #225
