### ISSUE TITLE
Remove DBid column visibility in Storage Portal and Donor Index

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#209]
Very minor change please, just for aesthetics:

Could the default be changed so that the DBid numbers are not visible in the Storage Portal and Donor Indexes? 

![image](https://user-images.githubusercontent.com/98022410/201328014-a1e6c335-00d0-4fea-b6f2-0636077daa2f.png)

**Comment by valbosco** [comment]
Fixed
