### ISSUE TITLE
Additional 'Diagnosis' filter

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#212]
Please could an additional filter be added to the Donor index for Diagnosis. I know that this can be searched for in the 'Search' box, but it would be nice to have a list of diagnoses as an option. 

For example, I could then filter by diagnosis, sex, race, age range (see other request), etc., and apply it all in one go:

![image](https://user-images.githubusercontent.com/98022410/201331278-e4f2626f-42cc-4050-9ede-6d73dc7c786b.png)

**Comment by pipaLU** [comment]
This should be to do with a better index/filter functions for donors.

**Comment by anthonyhorlock** [comment]
Thanks Chuan! Based on what I have seen in the TDCC Biobank database, we mostly need to be able to filter according to age, sex, diagnosis, sample type & 'Collection', to be able to identify how many donors we have. 

We then need to be able to filter out donors that haven't provided the appropriate consent for a particular use.  

If there are additional selections, such as BMI, as well as the detail from customisable attributes, I think we will have most things covered.

**Comment by KeironO** [comment]
We had a chat about this a couple days ago, the solution is to deploy a K/V lookup that'll contain DOID data. If you need help with this @valbosco drop me a message on Teams.

**Comment by valbosco** [comment]
> We had a chat about this a couple days ago, the solution is to deploy a K/V lookup that'll contain DOID data. If you need help with this @valbosco drop me a message on Teams.

Okay.

**Comment by valbosco** [comment]
Done
