### ISSUE TITLE
Add a customisable age range to the donor index

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#213]
Please could an additional age range selection be added into the donor index, so that we can filter according to Donors that fit within a particular range (e.g., 20 to 40 yrs old at registration):

![image](https://user-images.githubusercontent.com/98022410/201332039-448b8d41-e820-462b-a6f5-e91d1a9efc5b.png)

This could either be done via two boxes where we enter a 'from' and 'to', such as:

![image](https://user-images.githubusercontent.com/98022410/201332506-ba0fa2ce-5b02-4065-85f1-8267306371e1.png)

Alternatively, a sliding age range selector could also work:

![image](https://user-images.githubusercontent.com/98022410/201332011-45165640-c800-44b4-9c89-0fb3aecfc323.png)

**Comment by valbosco** [comment]
Fixed
