### ISSUE TITLE
Additional filter for sample types in the Donor Index

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#214]
Similar to the filter for sample types in the Sample Index, could this also be duplicated as a filter in the donor index?

It would be very useful to filter according to diagnosis, age, sex, etc., but then also be able to narrow it down to donors that also provided a specific sample type (e.g., Serum):

![image](https://user-images.githubusercontent.com/98022410/201333282-536a058d-3645-45ad-8fdd-0b32edcb79f0.png)

**Comment by pipaLU** [comment]
This has been achieved through sample index #248
