### ISSUE TITLE
Additional column in the Donor index for BMI

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#215]
Where BMI is currently calculated in the Donor Portal (from height & weight), it would be nice to see it in the Donor index too, as an additional column:

![image](https://user-images.githubusercontent.com/98022410/201333778-f213b21f-4003-46d3-90d3-ef2032493771.png)

![image](https://user-images.githubusercontent.com/98022410/201333569-2fd5b8ab-df2b-4cd6-836c-301dcb5a1d8e.png)

Perhaps we could filter BMI in the same way as age (see other request), or perhaps group it into categories:

![image](https://user-images.githubusercontent.com/98022410/201334623-e15e6766-a42b-433f-90c9-7024fa3e9358.png)

**Comment by valbosco** [comment]
Done
