### ISSUE TITLE
Master participant number as a default visibility in the Donor Index

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#218]
Please could the column for 'Master Participant Number' by assigned as visible by default in the Donor Index:

![image](https://user-images.githubusercontent.com/98022410/201345543-72246d30-2a05-4a6a-8b48-a5a4c03864f3.png)

We are on the line of thinking that LIMBDON ID would be treated as a 'Collection' for a particular diagnosis, as a fixed point in time for that particular donor. For example, each donor that provided Covid samples (even at multiple time points) would be assigned one LIMBDON ID. 

Therefore, if we have a participant that has donated Covid samples, but then returns later (perhaps years later) to provide samples for another reason (e.g., plasma samples for prostate cancer), we will assign them a second LIMBDON ID. 

We would then create a 'Master Participant Number' that would link these two (or more) LIMBDON ID's.

**Comment by valbosco** [comment]
Fixed

**Comment by anthonyhorlock** [comment]
Hi Ugwuoke,

I hope things are good with you!

I am not seeing these changes on my end. Will they be rolled out to me later?


Rwyf yn gweithio o ddydd Llun i ddydd Gwener 8am tan 4pm/Please Note that I work Monday to Friday 8 am until 4 pm


Kind regards



Dr Anthony Horlock

Ymarferydd Arbenigol Gwyddor Gofal Iechyd (Ymchwil)/Healthcare Science Practitioner Specialist (Research)

Bwrdd Iechyd Prifysgol Hywel Dda / Hywel Dda University Health Board

Yr Adran Ymchwil, Arloesedd, a GISW/Department of Research, Innovation, and VBHC

Canolfan Ymchwil Clinigol / Clinical Research Centre

Ysbyty Tywysog Philip / Prince Philip Hospital

Llanelli

SA14 8QF

________________________________
