### ISSUE TITLE
Filtering out donors that have not consented to a particular question type

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#220]
We need a way to be able to filter out Donors that have not consented to a particular question. I think the best way to deal with this is to do this according to question type. 

For example, if a Donor(s) does not want their samples to be subject to genetic testing, we would filter to remove these. This is pretty much the opposite of the filter that is currently present in the Sample Index:

![image](https://user-images.githubusercontent.com/98022410/201348760-3a24c417-a079-419f-bf12-93efa4f58eb9.png)

Please could this new filter be added to the Donor Index.

**Comment by pipaLU** [comment]
This has been achieved in sample index #248 , where samples can be filtered based on the consent questions.
