### ISSUE TITLE
Assign an attribute and documents directly to a Donor

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#222]
I think it would be very useful to be able to assign attributes and documents directly to the Donor, rather than the samples. 

We are treating each LIMBDON ID as a 'Collection'. Therefore, adding an additional attribute such as smoking status, or a copy of an anonymised pathology report, would make the process alot more efficient. 

![image](https://user-images.githubusercontent.com/98022410/201351663-292e73d3-1b5f-4a40-972f-4a42603ab723.png)

I created an attribute for smoking status, which I could assign to a sample:

![image](https://user-images.githubusercontent.com/98022410/201352688-f7da5391-13d8-4fc9-986e-f6479ea21275.png)

It would be great if this could be added to the Donor Portal in a similar manner!

Perhaps then, the customizable attributes included within the filter in the Donor Index, with an additional column in the table to indicate the answer/values?

**Comment by KeironO** [comment]
We could, but this would have to be after the January deadline.

**Comment by anthonyhorlock** [comment]
Please mark this for Version 2.0
