### ISSUE TITLE
Update sample barcodes directly from Biobank scanner output

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#223]
Is there a way that the rack barcodes could be updated directly from the file that is saved from the Biobank QR code scanner?

At the moment, I need to download the CSV file of the rack, manually update the barcodes, and then re-upload to LIMBUS. Could you take a look please?

I have attached an example file, for reference:

[G900167892.xls](https://github.com/AberystwythSystemsBiology/limbus/files/9990757/G900167892.xls)

**Comment by KeironO** [comment]
There's upload functionality within limbus for this.

Go into New Sample Rack and you'll find From File:

![image](https://user-images.githubusercontent.com/4386515/203622674-0a314bb6-853a-462a-b0fb-0b3d48c2e384.png)

Then you'll be greeted with this:

![image](https://user-images.githubusercontent.com/4386515/203622767-11a0fca5-1e37-4632-b0e8-c2314e7dfb78.png)

**Comment by anthonyhorlock** [comment]
Hi Keiron, 

The format of the spreadsheet that is exported from the Biobank scanner is not compatible with this upload function. 

As a result, to update the barcodes, I have to download the rack CSV and then manually copy across the barcodes from the Biobank scanner output. Then I re-upload the completed CSV file to update the barcodes. 

Is there a way to change things so that LIMBUS can decipher the file from the Biobank scanner, to update the barcodes?

**Comment by KeironO** [comment]
I'll investigate ASAP.

Which barcode scanner are you using now?

**Comment by anthonyhorlock** [comment]
Thanks, Keiron! 

We have the Greiner Bio-One ZTS CUBE-80
