### ISSUE TITLE
Diagnosis - Healthy Control

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#227]
Could we add a new diagnosis of 'Healthy Control', or 'Control'? 

I have some samples going into the Biobank, most of which came from patients with COPD. However, the others are considered as healthy controls.

![image](https://user-images.githubusercontent.com/98022410/202745437-b0fe46c2-c121-4c5b-b6b4-f74655314a7b.png)

**Comment by KeironO** [comment]
No need to add a diagnosis if the Donor is healthy ;-)
