### ISSUE TITLE
Bug with adding samples to cart

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#232]
The additional option to change the direction that samples are added to a cart, and the option to skip empty cells, seems to have disappeared. 

Additionally, are now automatically allocated horizontally, rather than vertically. 

Please can you take a look:

![image](https://user-images.githubusercontent.com/98022410/204555376-a13eab45-ca5e-4322-aa4b-bb434289aff0.png)

**Comment by pipaLU** [comment]
This should have been sorted by now.
