### ISSUE TITLE
Defaults not active for a project member

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#233]
I have delivered a training session on LIMBUS to a new member of the team (erin.bevan@wales.nhs.uk).

She does not seem to have the default settings that others have e.g., collection protocol, processing protocol, blood tube type, etc., 

Please could you look into this on her account, and any others that might be affected.

**Comment by pipaLU** [comment]
Checked the database and her setting is the same as others, and there should be no issues in this for adding sample collection or derivation.

**Comment by anthonyhorlock** [comment]
Thanks Chuan, I have asked her to create a new sample just to confirm.
