### ISSUE TITLE
Page scrolling when repositioning samples in a rack

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#234]
When moving samples to a new location in a rack, the page does not scroll with you. 

For example, if dragging a cell from the top of the rack to the bottom, I would need to deposit the sample somewhere in the middle and then scroll the rack down to finish the allocation. 

Could this be fixed so that the page scrolls with the user?

![image](https://user-images.githubusercontent.com/98022410/204556932-ac78e776-8ad4-4a48-8ce7-2c50b2b3decc.png)

**Comment by pipaLU** [comment]
If mouse is used, you can leave the mouse at the bottom of the page, wait for a second then it will scroll down. In chrome (from mac), one can drag and scroll the page at the same time. Perhaps this depends on the browser.

**Comment by anthonyhorlock** [comment]
Thanks Chuan. This appears to work fine on my work laptop!
