### ISSUE TITLE
Print function for rack setup

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#235]
Could an additional print function be added to a rack, so that the actual rack image (with the cell details) could be printed directly? 

![image](https://user-images.githubusercontent.com/98022410/204557405-c0c860f4-e0cc-43e0-b040-bac1fe13ef35.png)

This would be an alternative to the current print function that produces the list of samples:

![image](https://user-images.githubusercontent.com/98022410/204557686-e9ebaa70-2083-40cd-a854-0dad834c58c2.png)

**Comment by valbosco** [comment]
Done

**Comment by anthonyhorlock** [comment]
Thank-you!

**Comment by anthonyhorlock** [comment]
Can the print setup be in landscape mode, so that more of the cell detail can be seen?

**Comment by anthonyhorlock** [comment]
We can get by on this I think. We can always re-visit to modify it slightly in the future.
