### ISSUE TITLE
Delete attribute does not work

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#240]
Hello. The system won't let me delete attributes, even though the option is there:

![image](https://user-images.githubusercontent.com/98022410/205308839-c8e6b91b-d7ba-4bd9-9b6c-e35dacd81349.png)

**Comment by pipaLU** [comment]
Ok, this should work, but didn't display the error message.  Or sometimes it can't be deleted as there is associated samples. Will sort this out quickly.

**Comment by pipaLU** [comment]
#248
