### ISSUE TITLE
Sorting by Donor ID issue

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#241]
Good Morning, 

Since the DBID visibility has been removed from the Donor Index, I can no longer sort the Donors by LIMBDON ID. Please can you look in to this:

![image](https://user-images.githubusercontent.com/98022410/205590022-9fc536fd-b7eb-4dda-bfbb-6ab6d83ccb72.png)

**Comment by pipaLU** [comment]
sorted
