### ISSUE TITLE
Additional info on sample label

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#243]
In addition to the info that is currently printed on a sample label, please could the LIMBDON-ID be also included?

![image](https://user-images.githubusercontent.com/98022410/205937254-37c4a1a1-5df0-4465-9525-7780d60bdc2c.png)

**Comment by pipaLU** [comment]
It might be better to print the donor uuid instead of limbdon-id? but it depends on the purpose of the label. donor UUID is more unique transferred to different databases. We can also just print limbdon-id for local use and convenience.

**Comment by anthonyhorlock** [comment]
Thanks Chuan! This isn't essential, so perhaps we look at options in Version 2.0?

**Comment by anthonyhorlock** [comment]
I don't think we need to worry too much about this. I'll close this down and we can re-visit for Version 2 as a nice to do.
