### ISSUE TITLE
Can't create new samples

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#246]
Good Morning. I am getting this error when creating new samples; please can you take a look:

![image](https://user-images.githubusercontent.com/98022410/206659526-20f8c743-081b-4ce9-ade5-f408bc467442.png)

**Comment by pipaLU** [comment]
Fixed in the update.

**Comment by anthonyhorlock** [comment]
Perfect, thanks Chuan!
