### ISSUE TITLE
Can't delete samples

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#247]
Good Morning. I am getting this error when trying to delete samples; please can you take a look:

![image](https://user-images.githubusercontent.com/98022410/206659740-7e53d434-7b2f-4851-aeca-1592485b47af.png)

**Comment by pipaLU** [comment]
should be fixed by now.

**Comment by anthonyhorlock** [comment]
Hi Chuan, 

This has been fixed. Thank-you!
