### ISSUE TITLE
Error message when trying to edit a freezer

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#250]
Hello. 

I attempted to edit a freezer:

![image](https://user-images.githubusercontent.com/98022410/210542109-a625e98c-9eba-4136-8ff7-3f5a4e300761.png)

However, I got this error message:

'''Traceback (most recent call last):  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request    rv = self.dispatch_request()  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view    return func(*args, **kwargs)  File "/limbus/app/storage/routes/lts.py", line 210, in edit_cold_storage    if response.json()["content"]["is_locked"]:  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 898, in json    return complexjson.loads(self.text, **kwargs)  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads    return _default_decoder.decode(s)  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode    obj, end = self.raw_decode(s, idx=_w(s, 0).end())  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode    raise JSONDecodeError("Expecting value", s, err.value) from Nonejson.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 2)'''

Please could you take a look?

**Comment by pipaLU** [comment]
Sorted
