### ISSUE TITLE
Can't update racks from file 

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#252]
I'm trying to update the barcodes from file directly from the Biobank scanner output. 

Everything seems ok, until I try to update sample in rack when nothing happens. 

It's worked fine for some of the newer samples that have been created in the Biobank. Please could you look into this. 

I've also uploaded the CSV file that relates to this rack, for info. 

![image](https://user-images.githubusercontent.com/98022410/211537923-60149f25-94fb-4fc2-bec9-49036ddcb408.png)

[G900076102.csv](https://github.com/AberystwythSystemsBiology/limbus/files/10382010/G900076102.csv)

**Comment by anthonyhorlock** [comment]
Just to update. This is also an issue when I have downloaded the CSV for the rack and updated the barcodes manually. As above, the cells appear to update with the correct information. However, when I click on 'Update Sample in Rack', nothing happens:

![image](https://user-images.githubusercontent.com/98022410/211776057-d2a544f9-fb32-43cb-a6b7-e32e2526f220.png)

**Comment by pipaLU** [comment]
This should have been sorted now.

**Comment by anthonyhorlock** [comment]
Thanks Chuan, this seems to be working fine now!
