### ISSUE TITLE
Error adding rack to a shelf

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#256]
I am trying to assign racks to a shelf, but I get the following error message. Please can you take a look:

'''Traceback (most recent call last):  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request    rv = self.dispatch_request()  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view    return func(*args, **kwargs)  File "/limbus/app/storage/routes/shelf.py", line 322, in assign_racks_to_shelf    flash("We have a problem: %s" % (rack_move_response.json()))  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 898, in json    return complexjson.loads(self.text, **kwargs)  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads    return _default_decoder.decode(s)  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode    obj, end = self.raw_decode(s, idx=_w(s, 0).end())  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode    raise JSONDecodeError("Expecting value", s, err.value) from Nonejson.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 2)'''

**Comment by pipaLU** [comment]
This should have been sorted.
