### ISSUE TITLE
Sample status not changing following a sample review

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#257]
Hello. 

I was testing out the review function, and added a new sample review to some test samples (Unusable). However, the sample index did not update to reflect this. Please can you look into it for me:

![image](https://user-images.githubusercontent.com/98022410/213397085-3b9e8b6b-3223-461a-993e-6358b6e37994.png)

![image](https://user-images.githubusercontent.com/98022410/213397179-294d8ab2-cf02-4623-9ee0-85ad69027b9e.png)

![image](https://user-images.githubusercontent.com/98022410/213397275-fb51bbda-804c-46fc-b50a-e7356cb31910.png)

**Comment by pipaLU** [comment]
Can't reproduce this error. Perhaps the sample index page needs a refresh? In case of occasional incorrect sample status, you can use sample actions - Update status.

**Comment by anthonyhorlock** [comment]
Thanks Chuan!
