### ISSUE TITLE
Editing element type of attribute does not update

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#259]
I created a new attribute, with an element type of Donor. I then tried to edit the attribute, so that it could be assigned to all elements, but it isn't updating

![image](https://user-images.githubusercontent.com/98022410/213446145-b2372956-9169-4657-8335-e117a227988f.png)

Also, I had this error message when trying to assign another attribute to a sample:

'''Traceback (most recent call last):  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request    rv = self.dispatch_request()  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view    return func(*args, **kwargs)  File "/limbus/app/sample/routes/attribute.py", line 78, in new_custom_attribute_form    form = CustomAttributeGeneratedForm(attribute_ids)  File "/limbus/app/attribute/forms.py", line 339, in CustomAttributeGeneratedForm    ontologyNameError: name 'ontology' is not defined'''

**Comment by pipaLU** [comment]
only element type for sample has been implemented for the moment.
