### ISSUE TITLE
Sample alliquote

### ISSUE THREAD

**Issue by pipaLU** [AberystwythSystemsBiology/LImBuS#43]
**Describe the bug**

**To Reproduce**
1. Go to '.Sample-aliquote'
After pressing submit button, nothing happens in the frontend, but the error messages said null values for primary key when INSERT to table 

**Expected behavior**
Sub sample should be generated and ...

**Comment by KeironO** [comment]
Yeah, am able to reproduce. This wasn't like this last time I checked, and I've not changed any code in that for awhile - so might be something weird.

```
web_1  | sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "id" violates not-null constraint
web_1  | DETAIL:  Failing row contains (null, 2020-11-05 19:12:39.145045, f, 2020-11-05 19:12:39.145045, 2, 2, null, null).
web_1  |
web_1  | [SQL: INSERT INTO subsampletosample (is_locked, parent_id, subsample_id, author_id, editor_id) VALUES (%(is_locked)s, %(parent_id)s, %(subsample_id)s, %(author_id)s, %(editor_id)s)]
web_1  | [parameters: {'is_locked': False, 'parent_id': 2, 'subsample_id': 2, 'author_id': None, 'editor_id': None}]
web_1  | (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by KeironO** [comment]
Working on this now.

**Comment by KeironO** [comment]
![image](https://user-images.githubusercontent.com/4386515/98292627-e3b01f00-1fa4-11eb-93bf-9668aef7b1cd.png)

sqlalchemy doing sqlalchemy things.

I've "fixed" the issue in https://github.com/AberystwythSystemsBiology/limbus/pull/35/commits/424f1d0ea1ecc0331fa4609a26d39590e6b6e559, but I don't understand how.

If you don't want to trawl through that commit, I've added:

```
        ssts = SubSampleToSample(
            # wtf?
            id=1,
            parent_id = sample.id,
            subsample_id = sample_cpy.id,
            author_id = tokenuser.id
        )
```

Which works, but I don't like it at all - so I need to take a look at what in sweet jesus is happening there.

**Comment by KeironO** [comment]
@rob-a-bolton can you have a look @ this pls

**Comment by KeironO** [comment]
Actually, this is still borked.

**Comment by KeironO** [comment]
This was fixed in January, forgot to close.
