### ISSUE TITLE
Donor death_date cannot be handled going from edit route to edit api

### ISSUE THREAD

**Issue by rob-a-bolton** [AberystwythSystemsBiology/LImBuS#44]
**Describe the bug**
Receive following error attempting to update donor:
```
Notice! We have a problem: {'messages': {'death_date': ['Not a valid datetime.']}, 'success': False, 'type': 'Validation Error'} 
```

**To Reproduce**
1. Create donor
2. Edit donor
3. Click submit

**Expected behavior**
Donor should be updated correctly

**Comment by KeironO** [comment]
I am fairly certain that @pipaLU's revisions to the Donor blueprint fixed this, I'll double check at some point today - but not come up since November.

**Comment by pipaLU** [comment]
We can close this issue now, I think.

**Comment by KeironO** [comment]
I'll double check now, got caught up with other work.

**Comment by KeironO** [comment]
Works fine. The JavaScript on the edit form is a little clunky, but nothing that the user will notice. Will need sorting out, but very much something that needs fixing universally - using typescript.
