### ISSUE TITLE
[flufdon] Donor `updated_on` not automatically updated

### ISSUE THREAD

**Issue by rob-a-bolton** [AberystwythSystemsBiology/LImBuS#46]
**Describe the bug**
donor's `updated_on` field not updated automatically via `Base` model, requires manual update in `api.py`

**To Reproduce**
1. Remove/comment out `    donor.updated_on = func.now()` from "services/web/app/donor/api.py"
2. Add Donor
3. Edit Donor
4. Observe `donor.updated_on` values
5. No change on update unless `    donor.updated_on = func.now()` included

**Expected behavior**
As `Donor` inherits `Base`, this db column should be automatically updated

**Comment by KeironO** [comment]
Oh, bug confirmed.

Here's a Document...

```
{
  "content" : {
    "author" : {
      "email" : "me@domain.com",
      "first_name" : "Joe",
      "gravatar" : "https://www.gravatar.com/avatar/0ff2e377be7d73b15f0b48022a755717?s=20",
      "id" : 2,
      "last_name" : "Bloggs"
    },
    "created_on" : "2020-11-09",
    "description" : "",
    "files" : [
    ],
    "id" : 1,
    "is_locked" : false,
    "name" : "Example Document",
    "type" : "PATHO",
    "updated_on" : "2020-11-09T12:59:03.249821"
  },
  "success" : true
}
```

I've edited the description, but `updated_on` doesn't reflect the change.

```
{
  "content" : {
    "author" : {
      "email" : "me@domain.com",
      "first_name" : "Joe",
      "gravatar" : "https://www.gravatar.com/avatar/0ff2e377be7d73b15f0b48022a755717?s=20",
      "id" : 2,
      "last_name" : "Bloggs"
    },
    "created_on" : "2020-11-09",
    "description" : "Example Document Here",
    "files" : [
    ],
    "id" : 1,
    "is_locked" : false,
    "name" : "Example Document",
    "type" : "PATHO",
    "updated_on" : "2020-11-09T12:59:03.249821"
  },
  "success" : true
}
```

Strange. I've always had success with using `server_onupdate` in sqlalchemy!

Will look into it shortly. Thanks!

**Comment by KeironO** [comment]
This was fixed in the February release.
