### ISSUE TITLE
Bug during Sample Entry.

### ISSUE THREAD

**Issue by KeironO** [AberystwythSystemsBiology/LImBuS#62]
**Describe the bug**
Wrong message displayed after sample submitted successfully (can be viewed in the sample index): ‘... encountered errors’ 

**To Reproduce**
1. Enter a Sample
2. View Sample Index
3. See error

**Comment by KeironO** [comment]
I've been trying to reproduce this issue, but am unable to. I have noticed an issue with Sample Disposal information in the first form - I'm starting to think that we may not need to even need that in the first place - instead having two separate events.

One being an expected Sample Disposal event, and another being an actual Sample Disposal event. Thoughts @pipaLU ?

**Comment by pipaLU** [comment]
The initial sample disposal instruction and event might be relevant in new sample entry as there is certain time limit for preservation for some samples. It would be convenient to allow adding new disposal instruction and event (i.e. to modify the existing ones) after sample review.

**Comment by KeironO** [comment]
> The initial sample disposal instruction and event might be relevant in new sample entry as there is certain time limit for preservation for some samples. 

Yes, that's what I was referring to in regards to "expected" Sample Disposal. The "actual" Sample Disposal is events based.

**Comment by KeironO** [comment]
Yes, it's still broke. It's seemingly random, so I'll need to investigate.

**Comment by pipaLU** [comment]
Fixed. #96
