### ISSUE TITLE
Add action on sample: store samples to a rack. 

### ISSUE THREAD

**Issue by KeironO** [AberystwythSystemsBiology/LImBuS#64]
**Is your feature request related to a problem? Please describe.**
The user has requested that it should be possible to add a Sample to a rack directly through the Sample view.

**Comment by pipaLU** [comment]
#92 added a checkbox selection to sample view-lineage for the subsamples, allowing batch transfer with automated well location assignment, to a rack selected from a drop down box. Improvement would be needed in the future to allow setting more options, or manual adjustment.
