### ISSUE TITLE
Bad documentation on rack upload.

### ISSUE THREAD

**Issue by KeironO** [AberystwythSystemsBiology/LImBuS#65]
**Describe the bug**
@pipaLU's report states that:

> New rack by file uploading: errors? To check 

This is a little vague, but my testing this morning with the example datasets I was provided by the user doesn't indicate that a problem exists - may just be a documentation issue. Will email user today to find out more.

**Comment by KeironO** [comment]
I've checked this using the dataset that I was provided by HDUHB and it seems to work as intended.

@pipaLU can you liaise directly to find out what exact error was thrown?

**Comment by pipaLU** [comment]
It is indeed perhaps just a documentation issue.

**Comment by KeironO** [comment]
I've been testing this quite a bit, the errors that are returned are maybe a little too generic - but provided that the instructions are followed it works fine. I also feel like the instructions within the web page are pretty clear:

![image](https://user-images.githubusercontent.com/4386515/118955981-1923c500-b957-11eb-8408-fbffcc165141.png)

Ideally I'd have instructions on how to export as CSV in Microsoft Office, but I don't have access to a box with it installed. Do you happen to have access @pipaLU? If so, would you mind making a branch and writing it in similar fashion to how I've implemented it for LibreOffice.

**Comment by KeironO** [comment]
I hope this resolves the problem, but if it's still unclear then I'll just rewrite it to accept xlsx too.
