### ISSUE TITLE
Site management

### ISSUE THREAD

**Issue by pipaLU** [AberystwythSystemsBiology/LImBuS#68]
**Describe the bug**

**To Reproduce**
1. Go to Administrator Panel
2. Click on 'Site->Go'
3. Forwarded to user account info page. 

**Expected behavior**
Supposed to be able to change site info, or add a new site

**Additional context**
Adding new site to allow sample acquisition from multiple sites, and adding sample transfer location info.

**Comment by KeironO** [comment]
This was an oversight on my behalf, @rob-a-bolton 's changes to the Sample Storage centre did actually have a hyperlink to site creation - but we decided that it would be something best restricted to the administrator. I'll sort this out now.

**Comment by pipaLU** [comment]
The site here might not be a biobank, could be just a site for sample collection, or a research collaborator.

**Comment by KeironO** [comment]
Biobanks are Sites in the database (stored in the SiteInformation model). The api, forms and front end already exists - it's just a matter of linking it all up nicely.

**Comment by KeironO** [comment]
Turns out I deleted it when I re-did the views/api stuff.

**Comment by KeironO** [comment]
Sorted, thanks for the heads up @pipaLU
