### ISSUE TITLE
Aliquot sample rejigging

### ISSUE THREAD

**Issue by KeironO** [AberystwythSystemsBiology/LImBuS#76]
Two problems identified in user testing.

**Is your feature request related to a problem? Please describe.**
1. On page titled ‘Create Aliquoted Samples’ – container types will not be original blood collection tubes.
2. When a user corrects an error in the page, they have to manually scroll up.

**Describe the solution you'd like**

1. These will need to have the ability to be edited.  Containers will be secondary containers such as 1.5ml or 2ml microfuge tubes, 200ul tubes, 600ul tubes (like ones in the Biobank racks). 
2. Auto scroll to the top of the page to make the user aware of the changes.

**Describe alternatives you've considered**
Not applicable.

**Additional context**
Not applicable.

**Comment by pipaLU** [comment]
#92 change the enum type for container types of cell type (samples) to the long-term-preservation type (i.e. secondary container type) can solve many of the problems for the current user. However in longer term a customisable container would still be required.
