### ISSUE TITLE
Sample Transfer

### ISSUE THREAD

**Issue by KeironO** [AberystwythSystemsBiology/LImBuS#82]
**Is your feature request related to a problem? Please describe.**

There's currently no way in which we can transfer a sample from one institute to another.

**Describe the solution you'd like**

Have some form of cart system in place to facilitate the transfer of samples. This depends on Site management being implemented.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by KeironO** [comment]
Rightio, now that https://github.com/AberystwythSystemsBiology/limbus/pull/83 is merged - I can work on this.

**Comment by KeironO** [comment]
Added a partial implementation of this, still needs work.

**Comment by pipaLU** [comment]
Done in #94
