### ISSUE TITLE
Containers V2.0

### ISSUE THREAD

**Issue by KeironO** [AberystwythSystemsBiology/LImBuS#85]
**Is your feature request related to a problem? Please describe.**

It's obvious that the way in which we currently deal with containers is subpar. I'd have hoped that the existing standards would have sufficed, but it looks like there's a substantive amount of oversight there.

**Describe the solution you'd like**
Containers panel, allowing the user to define container information manually. This isn't going to be that complicated, but it's important that we get the schema right first time.

**Describe alternatives you've considered**
Not applicable.

**Additional context**

This is going to make migrating existing databases extremely difficult. There will have to be conversion scripts written to support this.

**Comment by KeironO** [comment]
Proposed model:

- UUID
- Name
- Manufacturer
- Suitable for (Cellular, Fluid, Tissue)
- Min Temperature
- Maximum Temperature
- Suitable for Sample Rack
- Colour

**Comment by rob-a-bolton** [comment]
* Size (?)
